<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0-windows10.0.17763.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UseWPF>true</UseWPF>
  </PropertyGroup>

  <ItemGroup>
    <Compile Remove="NetworkCore\**" />
    <Compile Remove="WPFTasks.Core\**" />
    <EmbeddedResource Remove="NetworkCore\**" />
    <EmbeddedResource Remove="WPFTasks.Core\**" />
    <None Remove="NetworkCore\**" />
    <None Remove="WPFTasks.Core\**" />
    <Page Remove="NetworkCore\**" />
    <Page Remove="WPFTasks.Core\**" />
  </ItemGroup>

  <ItemGroup>
    <None Remove="logo.png" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="ini-parser" Version="2.5.2" />
    <PackageReference Include="Microsoft.Data.SqlClient" Version="5.2.2" />
    <PackageReference Include="Microsoft.Toolkit.Uwp.Notifications" Version="7.1.3" />
    <PackageReference Include="MvvmCross" Version="9.2.0" />
    <PackageReference Include="Newtonsoft.Json" Version="13.0.3" />
  </ItemGroup>

  <ItemGroup>
    <Resource Include="logo.png" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="NetworkCore\TopNetwork.csproj" />
    <ProjectReference Include="WPFTasks.Core\WPFTasks.Core.csproj" />
  </ItemGroup>

</Project>
